site_name: October
site_author: Marcus Crane
site_description: >-
  Getting highlights off of your Kobo is very fiddly on a technical level. October is a community-driven desktop application that makes it really simple to send them to Readwise. 100% open source with support for Windows, macOS and Linux!
site_url: https://october.utf9k.net
repo_url: https://github.com/marcus-crane/october
repo_name: marcus-crane/october
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 Marcus Crane

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:october@utf9k.net
    - icon: fontawesome/brands/github
      link: https://github.com/marcus-crane/october
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sentreh

theme:
  name: material
  language: en
  logo: logo.png
  custom_dir: theme
  features:
    - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: marcus-crane/october
      branch: main
  - privacy:
      enabled: true
  - search
  - social

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Welcome: welcome.md
    - Prerequisites: prerequisites.md
    - Installation:
      - Linux: installation/linux.md
      - macOS: installation/macos.md
      - Windows: installation/windows.md
  - Extras:
    #   - Database Analysis: miscellaneous/database-analysis.md
    #   - Limitations: miscellaneous/limitations.md
    - License: miscellaneous/license.md
    - Reading Formats: miscellaneous/reading-formats.md
    - Thanks: thanks.md
    # - Contributions:
    #   - Bugs: contributions/bugs.md
    #   - Feature Requests: contributions/feature-requests.md
    #   - Questions: contributions/questions.md
  - Changelog: changelog/index.md
