// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildContentIndex(arg1, arg2) {
  return window['go']['backend']['Kobo']['BuildContentIndex'](arg1, arg2);
}

export function CountDeviceBookmarks(arg1) {
  return window['go']['backend']['Kobo']['CountDeviceBookmarks'](arg1);
}

export function ListDeviceBookmarks(arg1, arg2) {
  return window['go']['backend']['Kobo']['ListDeviceBookmarks'](arg1, arg2);
}

export function ListDeviceContent(arg1, arg2) {
  return window['go']['backend']['Kobo']['ListDeviceContent'](arg1, arg2);
}
