// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {slog} from '../models';

export function BuildContentIndex(arg1:Array<backend.Content>,arg2:slog.Logger):Promise<Record<string, backend.Content>>;

export function CountDeviceBookmarks(arg1:slog.Logger):Promise<backend.HighlightCounts>;

export function ListDeviceBookmarks(arg1:boolean,arg2:slog.Logger):Promise<Array<backend.Bookmark>>;

export function ListDeviceContent(arg1:boolean,arg2:slog.Logger):Promise<Array<backend.Content>>;
