// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function SendBookmarks(arg1:Array<backend.Response>,arg2:string):Promise<number>;
