// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Save() {
  return window['go']['backend']['Settings']['Save']();
}

export function SaveStoreHighlights(arg1) {
  return window['go']['backend']['Settings']['SaveStoreHighlights'](arg1);
}

export function SaveToken(arg1) {
  return window['go']['backend']['Settings']['SaveToken'](arg1);
}
