name: Publish docs
on:
  workflow_dispatch:
  push:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install social card dependencies
        run: sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install requests
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install git+https://${{ secrets.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git Pillow cairosvg
      - run: mkdocs build
      - name: Generate Netlify redirects file
        run: python scripts/generate-redirects.py
      - name: Publish to Cloudflare Pages
        id: cloudflare-publish
        if: ${{ !env.ACT }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 8e782a355544971b192db9e75d789dca
          projectName: 9koctober
          directory: site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: mshick/add-pr-comment@v2
        if: ${{ !env.ACT }}
        with:
          message: |
            🚀 This branch can be previewed at ${{ steps.cloudflare-publish.outputs.url }}
