name: Release October

on:
  pull_request:
    branches: [main]

jobs:
  release:
    strategy:
      matrix:
        build:
          # - platform: darwin/amd64
          #   os: macos-latest
          # - platform: darwin/arm64
          #   os: macos-latest
          # - platform: darwin/universal
          #   os: macos-latest
          - platform: linux/amd64
            os: ubuntu-latest
    runs-on: ${{ matrix.build.os }}
    name: Release October (${{ matrix.build.platform }})
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Normalise platform tag
        id: normalise_platform
        shell: bash
        run: |
          tag=$(echo ${{ matrix.build.platform }} | sed -e 's/\//_/g')
          echo "::set-output name=tag::$tag"

      - name: Normalise version tag
        id: normalise_version
        shell: bash
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            version=$(echo ${{ github.event.release.tag_name }} | sed -e 's/v//g')
          else
            version="1.0.0"
          fi
          echo "::set-output name=version::$version"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Install wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Ubuntu prerequisites
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.0'

      - name: Build frontend assets
        shell: bash
        run: |
          npm install -g npm
          node version.js "v${{ steps.normalise_version.outputs.version }}"
          cd frontend && npm install

      - name: Build wails app for Linux
        if: runner.os == 'Linux'
        shell: bash
        run: wails build -platform ${{ matrix.build.platform }} -ldflags "-X main.version=v${{ steps.normalise_version.outputs.version }}"
      
      - name: Package up deb file
        if: runner.os == 'Linux'
        shell: bash
        run: |
          mv build/bin/october build/linux/october_0.0.0_ARCH/usr/local/bin/
          cd build/linux
          sed -i 's/0.0.0/${{ steps.normalise_version.outputs.version }}/g' "october_0.0.0_ARCH/DEBIAN/control"
          sed -i 's/ARCH/amd64/g' "october_0.0.0_ARCH/DEBIAN/control"
          mv october_0.0.0_ARCH "october_${{ steps.normalise_version.outputs.version }}_amd64"
          dpkg-deb --build "october_${{ steps.normalise_version.outputs.version }}_amd64"
        
      - name: Upload build artifact
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v3
        with:
          name: october_pr${{ github.event.pull_request.number }}_${{ github.event.pull_request.head.sha }}_${{ steps.normalise_platform.outputs.tag }}
          path: |
            ./build/linux/october_${{ steps.normalise_version.outputs.version }}_amd64.deb

      - name: Get latest release from API
        if: startsWith(github.ref, 'refs/tags/')
        id: get_upload_url
        shell: bash
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/marcus-crane/october/releases" > /tmp/releases.json
          url=$(jq -r '.[0].upload_url' /tmp/releases.json)
          echo "::set-output name=url::$url"

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_NAME: october_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}
        with:
          upload_url:  ${{ steps.get_upload_url.outputs.url }}
          asset_path: ./build/linux/october_${{ steps.normalise_version.outputs.version }}_amd64.deb
          asset_name: ${{ env.ARTIFACT_NAME }}.deb
          asset_content_type: application/octet-stream
